[local]
localhost

[mongodb]
mongodb.devpreactice.online

[redis]
redis.devpreactice.online

[mysql]
mysql.devpreactice.online

[rabbitmq]
rabbitmq.devpreactice.online

[catalogue]
catalogue.devpreactice.online

[user]
user.devpreactice.online

[cart]
cart.devpreactice.online

[shipping]
shipping.devpreactice.online

[payment]
payment.devpreactice.online

[frontend]
frontend.devpreactice.online